[project]
name = "vision-project"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "torch (>=2.1.0,<3.0.0)",
    "torchvision (>=0.25.0,<0.26.0)",
    "numpy (>=2.4.2,<3.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "pandas (>=3.0.0,<4.0.0)",
    "tqdm (>=4.67.3,<5.0.0)",
    "pillow (>=10.0.0,<11.0.0)",
]

[tool.poetry]
packages = [{include = "vision_project", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "black (>=26.1.0,<27.0.0)",
    "ruff (>=0.15.1,<0.16.0)"
]

[tool.pytest.ini_options]
testpaths = ["tests"]